In [1]:
print("Machine learning provides {} the ability to learn {}".
    format("systems", "automatically"))

Machine learning provides systems the ability to learn automatically


In [2]:
t=[[1,2],[3,4],[5,6],[7,8],[9,10]]


In [3]:
c=1
for p in t:
    p[:]=p*2
    print(p)

[1, 2, 1, 2]
[3, 4, 3, 4]
[5, 6, 5, 6]
[7, 8, 7, 8]
[9, 10, 9, 10]


In [4]:
p

[9, 10, 9, 10]

In [5]:
from mxnet import np,npx

npx.set_np()

In [6]:
matriz=np.array([[1,2,3,4,5,6], [11,12,13,14,15,16]])
matriz,matriz.shape

[09:57:26] /home/mertins/Desenvolvimento/C/Terceiros/mxnet/src/storage/storage.cc:202: Using Pooled (Naive) StorageManager for CPU


(array([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [11., 12., 13., 14., 15., 16.]]),
 (2, 6))

[0,1],[5,4] =>    [0,5] = 6   &&   [1,4] = 15

=> [6,15]

In [25]:
matriz[[0,1],[5,4]]

array([ 6., 15.])

In [8]:
matriz.astype(('float32'))

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [11., 12., 13., 14., 15., 16.]])

In [9]:
teste=np.array([[False,True,True,True,False,True],[False,True,False,True,False,True]])
teste.astype('float32')

array([[0., 1., 1., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1.]])

In [10]:
resp=teste[0]==teste[1]
resp,resp.astype("float32").sum(),resp.astype("float32").sum()/len(resp)*100

(array([ True,  True, False,  True,  True,  True]), array(5.), array(83.33333))

In [11]:
[0,0] * 4

[0, 0, 0, 0, 0, 0, 0, 0]

In [38]:
m1=np.array([[1,2,3,4,5,6], [11,12,13,14,15,16]])

m2=np.array([100,1000])
m1.shape,m1,m2.shape,m2

((2, 6),
 array([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [11., 12., 13., 14., 15., 16.]]),
 (2,),
 array([ 100., 1000.]))

In [42]:
t=zip(m1,m2)
tuple(t)

((array([1., 2., 3., 4., 5., 6.]), array(100.)),
 (array([11., 12., 13., 14., 15., 16.]), array(1000.)))

In [39]:
m3=[a+b for a,b in zip(m1,m2)]
m3

[array([101., 102., 103., 104., 105., 106.]),
 array([1011., 1012., 1013., 1014., 1015., 1016.])]