## Introdução e preliminares 
Até a pg 61

In [8]:
import mxnet as mx
from mxnet import np, npx

In [9]:
npx.set_np()

In [10]:
x=np.arange(12)
x,type(x)

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 mxnet.numpy.ndarray)

In [11]:
x.shape

(12,)

In [12]:
x.size

12

In [13]:
x=x.reshape(3,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [14]:
X=np.arange(12).reshape(3,4)
Y=np.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [15]:
Y

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [16]:
np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X==Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [18]:
x=np.array([1,2,3]).reshape(3,1)
x

array([[1.],
       [2.],
       [3.]])

In [19]:
y=np.array([1,2]).reshape(1,2)
y

array([[1., 2.]])

In [20]:
x+y

array([[2., 3.],
       [3., 4.],
       [4., 5.]])

In [21]:
X,Y

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]))

In [22]:
X[-1]

array([ 8.,  9., 10., 11.])

In [23]:
X[1:3]

array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [24]:
X[0:3, 1:3]=13
X

array([[ 0., 13., 13.,  3.],
       [ 4., 13., 13.,  7.],
       [ 8., 13., 13., 11.]])

In [25]:
X>Y,X,Y

(array([[False,  True,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]),
 array([[ 0., 13., 13.,  3.],
        [ 4., 13., 13.,  7.],
        [ 8., 13., 13., 11.]]),
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]))

In [26]:
T1 = np.arange(12).reshape(1, 6, 2)
T1,np.arange(12)

(array([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [27]:
T2 = np.ones(shape=(6,6,1))
T2

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

## Data  Preprocessing 

pg 51

In [28]:
import os

In [29]:
os.makedirs(os.path.join('../../data','tmp'), exist_ok=True)

In [30]:
data_file=os.path.join('../../data','tmp','house_tiny.csv')

In [31]:
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') # Column names
    f.write('NA,Pave,127500\n') # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [32]:
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [33]:
inputs, outputs=data.iloc[:,0:2], data.iloc[:,2]
print(inputs)
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [34]:
inputs=pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [35]:
X, y=np.array(inputs.values), np.array(outputs.values)
X, y

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=float64),
 array([127500, 106000, 178100, 140000], dtype=int64))

### fazer exercicios da pg 53

In [36]:
t3=np.random.choice(np.array([1,2,np.nan]), (20, 5),p=np.array([0.4,0.4, 0.3]))
t3

array([[ 2.,  2.,  2., nan,  2.],
       [nan,  2., nan,  2.,  2.],
       [ 2.,  1.,  2.,  1., nan],
       [ 1., nan,  1.,  1.,  2.],
       [ 2., nan,  2.,  2.,  2.],
       [ 1., nan, nan,  1.,  1.],
       [ 1.,  2.,  1.,  1., nan],
       [nan,  2.,  1., nan, nan],
       [nan,  2.,  2., nan,  2.],
       [ 2.,  2.,  2.,  1.,  2.],
       [ 2.,  2.,  1.,  2., nan],
       [ 2.,  2.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.,  2.],
       [ 1.,  2.,  1.,  1.,  1.],
       [ 2.,  1.,  2.,  1.,  2.],
       [ 1., nan, nan,  2.,  2.],
       [ 1.,  2.,  2., nan,  2.],
       [ 1.,  1., nan,  2.,  2.],
       [ 2.,  1.,  1.,  1.,  1.],
       [ 2.,  1.,  2.,  1.,  1.]])

In [37]:
df=pd.DataFrame(t3.asnumpy(),columns=['a','b','c','e','f'])
print(df)

      a    b    c    e    f
0   2.0  2.0  2.0  NaN  2.0
1   NaN  2.0  NaN  2.0  2.0
2   2.0  1.0  2.0  1.0  NaN
3   1.0  NaN  1.0  1.0  2.0
4   2.0  NaN  2.0  2.0  2.0
5   1.0  NaN  NaN  1.0  1.0
6   1.0  2.0  1.0  1.0  NaN
7   NaN  2.0  1.0  NaN  NaN
8   NaN  2.0  2.0  NaN  2.0
9   2.0  2.0  2.0  1.0  2.0
10  2.0  2.0  1.0  2.0  NaN
11  2.0  2.0  1.0  2.0  2.0
12  1.0  1.0  2.0  2.0  2.0
13  1.0  2.0  1.0  1.0  1.0
14  2.0  1.0  2.0  1.0  2.0
15  1.0  NaN  NaN  2.0  2.0
16  1.0  2.0  2.0  NaN  2.0
17  1.0  1.0  NaN  2.0  2.0
18  2.0  1.0  1.0  1.0  1.0
19  2.0  1.0  2.0  1.0  1.0


In [38]:
df.isnull().mean()

a    0.15
b    0.20
c    0.20
e    0.20
f    0.20
dtype: float64

In [39]:
df.columns[df.isnull().mean() < 0.25]

Index(['a', 'b', 'c', 'e', 'f'], dtype='object')

In [40]:
res1=df[df.columns[df.isnull().mean() < 0.25]]
print(res1)

      a    b    c    e    f
0   2.0  2.0  2.0  NaN  2.0
1   NaN  2.0  NaN  2.0  2.0
2   2.0  1.0  2.0  1.0  NaN
3   1.0  NaN  1.0  1.0  2.0
4   2.0  NaN  2.0  2.0  2.0
5   1.0  NaN  NaN  1.0  1.0
6   1.0  2.0  1.0  1.0  NaN
7   NaN  2.0  1.0  NaN  NaN
8   NaN  2.0  2.0  NaN  2.0
9   2.0  2.0  2.0  1.0  2.0
10  2.0  2.0  1.0  2.0  NaN
11  2.0  2.0  1.0  2.0  2.0
12  1.0  1.0  2.0  2.0  2.0
13  1.0  2.0  1.0  1.0  1.0
14  2.0  1.0  2.0  1.0  2.0
15  1.0  NaN  NaN  2.0  2.0
16  1.0  2.0  2.0  NaN  2.0
17  1.0  1.0  NaN  2.0  2.0
18  2.0  1.0  1.0  1.0  1.0
19  2.0  1.0  2.0  1.0  1.0


In [41]:
resInput=np.array(res1.values)
resOutput=np.random.rand(20)
resInput,resOutput

(array([[ 2.,  2.,  2., nan,  2.],
        [nan,  2., nan,  2.,  2.],
        [ 2.,  1.,  2.,  1., nan],
        [ 1., nan,  1.,  1.,  2.],
        [ 2., nan,  2.,  2.,  2.],
        [ 1., nan, nan,  1.,  1.],
        [ 1.,  2.,  1.,  1., nan],
        [nan,  2.,  1., nan, nan],
        [nan,  2.,  2., nan,  2.],
        [ 2.,  2.,  2.,  1.,  2.],
        [ 2.,  2.,  1.,  2., nan],
        [ 2.,  2.,  1.,  2.,  2.],
        [ 1.,  1.,  2.,  2.,  2.],
        [ 1.,  2.,  1.,  1.,  1.],
        [ 2.,  1.,  2.,  1.,  2.],
        [ 1., nan, nan,  2.,  2.],
        [ 1.,  2.,  2., nan,  2.],
        [ 1.,  1., nan,  2.,  2.],
        [ 2.,  1.,  1.,  1.,  1.],
        [ 2.,  1.,  2.,  1.,  1.]]),
 array([0.57019675, 0.03842543, 0.43860152, 0.63427407, 0.9883738 ,
        0.95894927, 0.10204481, 0.6527903 , 0.20887676, 0.6350589 ,
        0.16130951, 0.9952996 , 0.6531083 , 0.58185035, 0.2532916 ,
        0.4143686 , 0.46631077, 0.4746975 , 0.2444256 , 0.6235101 ]))

## Linear Algebra
pg 53

In [42]:
A=np.arange(20).reshape(5,4)
A,A.mean(axis=0),A.mean(axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]),
 array([ 8.,  9., 10., 11.]),
 array([ 1.5,  5.5,  9.5, 13.5, 17.5]))

In [43]:
A.sum(),A.sum(axis=1),A.sum(axis=1,keepdims=True)

(array(190.),
 array([ 6., 22., 38., 54., 70.]),
 array([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]]))

In [44]:
A/A.sum(axis=1,keepdims=True),A.cumsum(axis=1)

(array([[0.        , 0.16666667, 0.33333334, 0.5       ],
        [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
        [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
        [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
        [0.22857143, 0.24285714, 0.25714287, 0.27142859]]),
 array([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]]))

### Produto Hadamard (Element-wise) e Produto de Matriz
           *                               dot
           

In [45]:
A1=np.array([1,2,3,4]).reshape(2,2)
B1=np.array([-1,3,4,2]).reshape(2,2)
A1,B1,A1*B1,np.dot(A1,B1),np.dot(B1,A1)

(array([[1., 2.],
        [3., 4.]]),
 array([[-1.,  3.],
        [ 4.,  2.]]),
 array([[-1.,  6.],
        [12.,  8.]]),
 array([[ 7.,  7.],
        [13., 17.]]),
 array([[ 8., 10.],
        [10., 16.]]))

In [46]:
A1=np.array([1,2,3,4])
B1=np.array([-1,3,4,2])
A1,B1,A1*B1,np.dot(A1,B1)

(array([1., 2., 3., 4.]),
 array([-1.,  3.,  4.,  2.]),
 array([-1.,  6., 12.,  8.]),
 array(25.))

In [47]:
y=np.ones(4)
x.reshape(1,3), y

(array([[1., 2., 3.]]), array([1., 1., 1., 1.]))

### Norm 
pg 63

<https://www.ime.unicamp.br/~valle/Teaching/MS211/Aula05.pdf>   - norma vetorial



### Norm L2
\[3,-4]

sqrt{3² + -4²}=5
  

In [48]:
u=np.array([3,-4])
u,np.linalg.norm(u)

(array([ 3., -4.]), array(5.))

###Norm L1

\[3,-4]

|3|+|-4|=7


In [49]:
np.abs(u).sum()

array(7.)

### Frobenius norm 
Aplica a L2 sobre Matrizes


### Exercícios pg 65

#### Confrontar com https://hy38.github.io/D2L-2-linear-algebra


#### 1. Prove that the transpose of a matrix A’s transpose is A : (𝐀T)⊤=A(𝐀^T)^⊤ = A(AT)⊤=A

In [50]:
A=np.arange(25).reshape(5,5)
AT=A.T
TA=AT.T
res=(A==TA).reshape(A.size)
#type(res),type(res.asnumpy()),
#np.diff(res,prepend=False, append=False)
np.count_nonzero(res%2==1)==A.size


True


#### 2. Given two matrices A and B, show that the sum of transposes is equal to the transpose of a sum: A⊤+B⊤= (A+B)⊤


In [51]:
A1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
A2=A1.copy()
B1=np.array([2,4,6,8,10,12,14,16,18]).reshape(3,3)
B2=B1.copy()
A1,A2,B1,B2

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 array([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]]),
 array([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]]))

In [52]:
R1=A1.T + B1.T
R2=(A1+B1).T
res=(R1==R2).reshape(R1.size)
np.count_nonzero(res%2==1)==R1.size

True

#### 3. Given any square matrixA, is A+A⊤ always symmetric? Why?


In [53]:
t1=A1+A1.T
t2=B1+B1.T
res1=(t1==t1.T).reshape(t1.size)
res2=(t2==t2.T).reshape(t2.size)
res1,res2
np.count_nonzero(res1%2==1)==res1.size , np.count_nonzero(res2%2==1)==res2.size

(True, True)

#### 4. We defined the tensorX 
of shape (2, 3, 4) in this section. What is the output oflen(X)?

In [54]:
T=np.ones((2,3,4))
T,T.size,T.shape

(array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]),
 24,
 (2, 3, 4))

#### 5. For a tensorXof arbitrary shape, does len(X) always correspond to the length of a certain axis ofX? What is that axis?
first

#### 6.Run A / A.sum(axis=1) 
and see what happens. Can you analyze the reason?

In [55]:
t=A.sum(axis=1)
A,t,A/t

(array([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]]),
 array([ 10.,  35.,  60.,  85., 110.]),
 array([[0.        , 0.02857143, 0.03333334, 0.03529412, 0.03636364],
        [0.5       , 0.17142858, 0.11666667, 0.09411765, 0.08181818],
        [1.        , 0.31428573, 0.2       , 0.15294118, 0.12727273],
        [1.5       , 0.45714286, 0.28333333, 0.21176471, 0.17272727],
        [2.        , 0.6       , 0.36666667, 0.27058825, 0.21818182]]))

#### 8. Consider a tensor with shape (2, 3, 4). What are the shapes of the summation outputs alongaxis 0, 1, and 2?

In [56]:
A=mx.nd.arange(1,25).reshape(2,3,4)
A,A.sum(0),A.sum(1),A.sum(2)

(
 [[[ 1.  2.  3.  4.]
   [ 5.  6.  7.  8.]
   [ 9. 10. 11. 12.]]
 
  [[13. 14. 15. 16.]
   [17. 18. 19. 20.]
   [21. 22. 23. 24.]]]
 <NDArray 2x3x4 @cpu(0)>,
 
 [[14. 16. 18. 20.]
  [22. 24. 26. 28.]
  [30. 32. 34. 36.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[15. 18. 21. 24.]
  [51. 54. 57. 60.]]
 <NDArray 2x4 @cpu(0)>,
 
 [[10. 26. 42.]
  [58. 74. 90.]]
 <NDArray 2x3 @cpu(0)>)

#### 9. Feed a tensor with 3 or more axes to the linalg.norm function and observe its output. Whatdoes this function compute for tensors of arbitrary shape?
https://www.educative.io/edpresso/what-is-the-nplinalgnorm-method-in-numpy


In [57]:
A=(np.arange(24)-5).reshape(2,3,4)
A , np.linalg.norm(A),np.linalg.norm(A,axis=0),np.linalg.norm(A,axis=1),np.linalg.norm(A,axis=2)

(array([[[-5., -4., -3., -2.],
         [-1.,  0.,  1.,  2.],
         [ 3.,  4.,  5.,  6.]],
 
        [[ 7.,  8.,  9., 10.],
         [11., 12., 13., 14.],
         [15., 16., 17., 18.]]]),
 array(46.518814),
 array([[ 8.602325,  8.944272,  9.486833, 10.198039],
        [11.045361, 12.      , 13.038405, 14.142136],
        [15.297058, 16.492422, 17.720043, 18.973665]]),
 array([[ 5.91608  ,  5.656854 ,  5.91608  ,  6.6332493],
        [19.874607 , 21.540659 , 23.216373 , 24.899797 ]]),
 array([[ 7.3484697,  2.4494898,  9.273619 ],
        [17.146427 , 25.0998   , 33.075672 ]]))