# 3.6 Softmax regression from scratch

In [3]:
from IPython import display
from mxnet import autograd, gluon, np, npx
from d2l import mxnet as d2l

npx.set_np()

In [4]:
batch_size=256
train_iter, test_iter=d2l.load_data_fashion_mnist(batch_size)

In [6]:
num_inputs=784
num_outputs=10

w=np.random.normal(0,0.01,(num_inputs,num_outputs))
b=np.zeros(num_outputs)
w.attach_grad()
b.attach_grad()

In [12]:
X=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
X.shape,X.sum(0,keepdims=True),X.sum(1,keepdims=True)

((2, 3),
 array([[5., 7., 9.]]),
 array([[ 6.],
        [15.]]))

In [13]:
def softmax(X):
    X_exp=np.exp(X)
    partition = X_exp.sum(1,keepdims=True)
    return X_exp/partition

In [28]:
X = np.random.normal(0,1,(2,5))
X_prob = softmax(X)
X,X_prob, X_prob.sum(1)

(array([[ 0.06246768, -0.6872371 , -0.71223146,  1.8696269 , -0.8538647 ],
        [-1.9289527 , -0.8557522 , -0.09219167,  0.25186515, -1.4885172 ]]),
 array([[0.11867401, 0.05607418, 0.05469002, 0.7230942 , 0.04746763],
        [0.04852525, 0.141923  , 0.304553  , 0.4296204 , 0.07537832]]),
 array([1.        , 0.99999994]))

In [29]:
def net(X):
    return softmax(np.dot(X.reshape((-1,W.shape[0])),W)+b)