# 3.6 Softmax regression from scratch

In [10]:
from IPython import display
from mxnet import autograd, gluon, np, npx
from d2l import mxnet as d2l

npx.set_np()

In [11]:
batch_size=256
train_iter, test_iter=d2l.load_data_fashion_mnist(batch_size)

[ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/core/src/parallel/registry_parallel.impl.hpp (96) ParallelBackendRegistry core(parallel): Enabled backends(2, sorted by priority): TBB(1000); OPENMP(990)
[ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/core/include/opencv2/core/parallel/backend/parallel_for.tbb.hpp (54) ParallelForBackend Initializing TBB parallel backend: TBB_INTERFACE_VERSION=11103
[ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/core/src/parallel/parallel.cpp (77) createParallelForAPI core(parallel): using backend: TBB (priority=1000)
[ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/core/src/parallel/registry_parallel.impl.hpp (96) ParallelBackendRegistry core(parallel): Enabled backends(2, sorted by priority): TBB(1000); OPENMP(990)
[ INFO:0] global /builddir/build/BUILD/opencv-4.5.3/modules/core/include/opencv2/core/parallel/backend/parallel_for.tbb.hpp (54) ParallelForBackend Initializing TBB parallel backend: TBB_INTERF

In [12]:
num_inputs=784
num_outputs=10

w=np.random.normal(0,0.01,(num_inputs,num_outputs))
b=np.zeros(num_outputs)
w.attach_grad()
b.attach_grad()

In [13]:
X=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
X.shape,X.sum(0,keepdims=True),X.sum(1,keepdims=True)

((2, 3),
 array([[5., 7., 9.]]),
 array([[ 6.],
        [15.]]))

In [14]:
def softmax(X):
    X_exp=np.exp(X)
    partition = X_exp.sum(1,keepdims=True)
    return X_exp/partition

In [15]:
X = np.random.normal(0,1,(2,5))
X_prob = softmax(X)
X,X_prob, X_prob.sum(1)

(array([[-1.1623443 , -0.11915815,  1.7739077 , -0.9122774 , -1.0591689 ],
        [ 0.2307472 ,  1.7626199 , -0.6483015 ,  0.7464437 , -0.2100258 ]]),
 array([[0.03987857, 0.11318518, 0.7515149 , 0.05120853, 0.04421281],
        [0.11961216, 0.5534255 , 0.0496603 , 0.200327  , 0.07697506]]),
 array([1., 1.]))

In [16]:
def net(X):
    return softmax(np.dot(X.reshape((-1,W.shape[0])),W)+b)

# Loss function

In [17]:
y=np.array([0,2])
y_hat=np.array([[0.1,0.3,0.6],[0.3,0.2,0.5]])
y_hat[[0,1],y]

array([0.1, 0.5])

In [18]:
def cross_entropy(y_hat,y):
    return -np.log(y_hat[range(len(y_hat)),y])

cross_entropy(y_hat,y)

array([2.3025851, 0.6931472])

#### 3.6.5 Classification Accuracy

In [21]:
def accuracy(y_hat,y):
    if (len(y_hat.shape)>1 and y_hat.shape[1]>1):
        y_hat=y_hat.argmax(axis=1)
    cmp=y_hat.astype(y.dtype)==y
    return float(cmp.astype(y.dtype).sum())

In [22]:
accuracy(y_hat, y)/len(y)

0.5