## Introdução e prelinares

In [61]:
import mxnet as mx
from mxnet import np, npx

In [69]:
npx.set_np()

In [70]:
x=np.arange(12)
x,type(x)

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 mxnet.numpy.ndarray)

In [71]:
x.shape

(12,)

In [5]:
x.size

12

In [6]:
x=x.reshape(3,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [7]:
X=np.arange(12).reshape(3,4)
Y=np.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [8]:
Y

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [9]:
np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [10]:
X==Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [11]:
x=np.array([1,2,3]).reshape(3,1)
x

array([[1.],
       [2.],
       [3.]])

In [12]:
y=np.array([1,2]).reshape(1,2)
y

array([[1., 2.]])

In [13]:
x+y

array([[2., 3.],
       [3., 4.],
       [4., 5.]])

In [14]:
X,Y

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]))

In [15]:
X[-1]

array([ 8.,  9., 10., 11.])

In [16]:
X[1:3]

array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [17]:
X[0:3, 1:3]=13
X

array([[ 0., 13., 13.,  3.],
       [ 4., 13., 13.,  7.],
       [ 8., 13., 13., 11.]])

In [20]:
X>Y,X,Y

(array([[False,  True,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]),
 array([[ 0., 13., 13.,  3.],
        [ 4., 13., 13.,  7.],
        [ 8., 13., 13., 11.]]),
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]))

In [24]:
T1 = np.arange(12).reshape(1, 6, 2)
T1,np.arange(12)

(array([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [23]:
T2 = np.ones(shape=(6,6,1))
T2

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

## Data  Preprocessing 

pg 51

In [25]:
import os

In [27]:
os.makedirs(os.path.join('../../data','tmp'), exist_ok=True)

In [36]:
data_file=os.path.join('../../data','tmp','house_tiny.csv')

In [37]:
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') # Column names
    f.write('NA,Pave,127500\n') # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [38]:
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [45]:
inputs, outputs=data.iloc[:,0:2], data.iloc[:,2]
print(inputs)
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [46]:
inputs=pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [47]:
X, y=np.array(inputs.values), np.array(outputs.values)
X, y

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=float64),
 array([127500, 106000, 178100, 140000], dtype=int64))

In [171]:
t3=np.random.choice(np.array([1,2,np.nan]), (20, 5),p=np.array([0.4,0.4, 0.2]))
t3

array([[ 2.,  1.,  1.,  2.,  2.],
       [ 2.,  1., nan,  1.,  1.],
       [ 1.,  2.,  1.,  2.,  1.],
       [ 1.,  2.,  2.,  1., nan],
       [ 1.,  1.,  2.,  1.,  2.],
       [ 1.,  2., nan,  2.,  2.],
       [ 1., nan,  2.,  2.,  2.],
       [nan, nan,  1.,  1.,  1.],
       [ 2.,  1., nan,  2., nan],
       [ 1.,  1., nan,  2., nan],
       [ 1.,  1.,  2.,  1.,  1.],
       [ 1., nan,  1.,  1.,  1.],
       [ 2.,  2.,  1., nan,  1.],
       [ 1.,  1.,  2., nan, nan],
       [ 1.,  2.,  1.,  2.,  2.],
       [ 2., nan, nan,  2.,  2.],
       [nan,  1.,  2.,  1.,  2.],
       [ 2., nan,  2.,  1.,  2.],
       [ 1.,  2.,  1.,  2.,  2.],
       [ 2.,  1.,  1., nan, nan]])

In [180]:
df=pd.DataFrame(t3.asnumpy(),columns=['a','b','c','e','f'])
print(df)

      a    b    c    e    f
0   2.0  1.0  1.0  2.0  2.0
1   2.0  1.0  NaN  1.0  1.0
2   1.0  2.0  1.0  2.0  1.0
3   1.0  2.0  2.0  1.0  NaN
4   1.0  1.0  2.0  1.0  2.0
5   1.0  2.0  NaN  2.0  2.0
6   1.0  NaN  2.0  2.0  2.0
7   NaN  NaN  1.0  1.0  1.0
8   2.0  1.0  NaN  2.0  NaN
9   1.0  1.0  NaN  2.0  NaN
10  1.0  1.0  2.0  1.0  1.0
11  1.0  NaN  1.0  1.0  1.0
12  2.0  2.0  1.0  NaN  1.0
13  1.0  1.0  2.0  NaN  NaN
14  1.0  2.0  1.0  2.0  2.0
15  2.0  NaN  NaN  2.0  2.0
16  NaN  1.0  2.0  1.0  2.0
17  2.0  NaN  2.0  1.0  2.0
18  1.0  2.0  1.0  2.0  2.0
19  2.0  1.0  1.0  NaN  NaN


### fazer exercicios da pg 53