In [1]:
from mxnet import np, npx

In [2]:
npx.set_np()

In [3]:
x=np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.shape

(12,)

In [5]:
x.size

12

In [6]:
x=x.reshape(3,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [15]:
X=np.arange(12).reshape(3,4)
Y=np.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [11]:
Y

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [12]:
np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
X==Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
x=np.array([1,2,3]).reshape(3,1)
x

array([[1.],
       [2.],
       [3.]])

In [23]:
y=np.array([1,2]).reshape(1,2)
y

array([[1., 2.]])

In [24]:
x+y

array([[2., 3.],
       [3., 4.],
       [4., 5.]])

In [26]:
X,Y

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]))

In [27]:
X[-1]

array([ 8.,  9., 10., 11.])

In [29]:
X[1:3]

array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [32]:
X[0:3, 1:3]=13
X

array([[12., 13., 13., 12.],
       [12., 13., 13., 12.],
       [12., 13., 13., 12.]])