## Introdução e prelinares

In [1]:
import mxnet as mx
from mxnet import np, npx

In [2]:
npx.set_np()

In [3]:
x=np.arange(12)
x,type(x)

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 mxnet.numpy.ndarray)

In [4]:
x.shape

(12,)

In [5]:
x.size

12

In [6]:
x=x.reshape(3,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [7]:
X=np.arange(12).reshape(3,4)
Y=np.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [8]:
Y

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [9]:
np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [10]:
X==Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [11]:
x=np.array([1,2,3]).reshape(3,1)
x

array([[1.],
       [2.],
       [3.]])

In [12]:
y=np.array([1,2]).reshape(1,2)
y

array([[1., 2.]])

In [13]:
x+y

array([[2., 3.],
       [3., 4.],
       [4., 5.]])

In [14]:
X,Y

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]))

In [15]:
X[-1]

array([ 8.,  9., 10., 11.])

In [16]:
X[1:3]

array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [17]:
X[0:3, 1:3]=13
X

array([[ 0., 13., 13.,  3.],
       [ 4., 13., 13.,  7.],
       [ 8., 13., 13., 11.]])

In [18]:
X>Y,X,Y

(array([[False,  True,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]),
 array([[ 0., 13., 13.,  3.],
        [ 4., 13., 13.,  7.],
        [ 8., 13., 13., 11.]]),
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]))

In [19]:
T1 = np.arange(12).reshape(1, 6, 2)
T1,np.arange(12)

(array([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [20]:
T2 = np.ones(shape=(6,6,1))
T2

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

## Data  Preprocessing 

pg 51

In [21]:
import os

In [22]:
os.makedirs(os.path.join('../../data','tmp'), exist_ok=True)

In [23]:
data_file=os.path.join('../../data','tmp','house_tiny.csv')

In [24]:
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') # Column names
    f.write('NA,Pave,127500\n') # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [25]:
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [26]:
inputs, outputs=data.iloc[:,0:2], data.iloc[:,2]
print(inputs)
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [27]:
inputs=pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [28]:
X, y=np.array(inputs.values), np.array(outputs.values)
X, y

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=float64),
 array([127500, 106000, 178100, 140000], dtype=int64))

### fazer exercicios da pg 53

In [29]:
t3=np.random.choice(np.array([1,2,np.nan]), (20, 5),p=np.array([0.4,0.4, 0.3]))
t3

array([[ 2.,  2.,  2., nan,  2.],
       [nan,  2., nan,  2.,  2.],
       [ 2.,  1.,  2.,  1., nan],
       [ 1., nan,  1.,  1.,  2.],
       [ 2., nan,  2.,  2.,  2.],
       [ 1., nan, nan,  1.,  1.],
       [ 1.,  2.,  1.,  1., nan],
       [nan,  2.,  1., nan, nan],
       [nan,  2.,  2., nan,  2.],
       [ 2.,  2.,  2.,  1.,  2.],
       [ 2.,  2.,  1.,  2., nan],
       [ 2.,  2.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.,  2.],
       [ 1.,  2.,  1.,  1.,  1.],
       [ 2.,  1.,  2.,  1.,  2.],
       [ 1., nan, nan,  2.,  2.],
       [ 1.,  2.,  2., nan,  2.],
       [ 1.,  1., nan,  2.,  2.],
       [ 2.,  1.,  1.,  1.,  1.],
       [ 2.,  1.,  2.,  1.,  1.]])

In [30]:
df=pd.DataFrame(t3.asnumpy(),columns=['a','b','c','e','f'])
print(df)

      a    b    c    e    f
0   2.0  2.0  2.0  NaN  2.0
1   NaN  2.0  NaN  2.0  2.0
2   2.0  1.0  2.0  1.0  NaN
3   1.0  NaN  1.0  1.0  2.0
4   2.0  NaN  2.0  2.0  2.0
5   1.0  NaN  NaN  1.0  1.0
6   1.0  2.0  1.0  1.0  NaN
7   NaN  2.0  1.0  NaN  NaN
8   NaN  2.0  2.0  NaN  2.0
9   2.0  2.0  2.0  1.0  2.0
10  2.0  2.0  1.0  2.0  NaN
11  2.0  2.0  1.0  2.0  2.0
12  1.0  1.0  2.0  2.0  2.0
13  1.0  2.0  1.0  1.0  1.0
14  2.0  1.0  2.0  1.0  2.0
15  1.0  NaN  NaN  2.0  2.0
16  1.0  2.0  2.0  NaN  2.0
17  1.0  1.0  NaN  2.0  2.0
18  2.0  1.0  1.0  1.0  1.0
19  2.0  1.0  2.0  1.0  1.0


In [31]:
df.isnull().mean()

a    0.15
b    0.20
c    0.20
e    0.20
f    0.20
dtype: float64

In [32]:
df.columns[df.isnull().mean() < 0.25]

Index(['a', 'b', 'c', 'e', 'f'], dtype='object')

In [33]:
res1=df[df.columns[df.isnull().mean() < 0.25]]
print(res1)

      a    b    c    e    f
0   2.0  2.0  2.0  NaN  2.0
1   NaN  2.0  NaN  2.0  2.0
2   2.0  1.0  2.0  1.0  NaN
3   1.0  NaN  1.0  1.0  2.0
4   2.0  NaN  2.0  2.0  2.0
5   1.0  NaN  NaN  1.0  1.0
6   1.0  2.0  1.0  1.0  NaN
7   NaN  2.0  1.0  NaN  NaN
8   NaN  2.0  2.0  NaN  2.0
9   2.0  2.0  2.0  1.0  2.0
10  2.0  2.0  1.0  2.0  NaN
11  2.0  2.0  1.0  2.0  2.0
12  1.0  1.0  2.0  2.0  2.0
13  1.0  2.0  1.0  1.0  1.0
14  2.0  1.0  2.0  1.0  2.0
15  1.0  NaN  NaN  2.0  2.0
16  1.0  2.0  2.0  NaN  2.0
17  1.0  1.0  NaN  2.0  2.0
18  2.0  1.0  1.0  1.0  1.0
19  2.0  1.0  2.0  1.0  1.0


In [34]:
resInput=np.array(res1.values)
resOutput=np.random.rand(20)
resInput,resOutput

(array([[ 2.,  2.,  2., nan,  2.],
        [nan,  2., nan,  2.,  2.],
        [ 2.,  1.,  2.,  1., nan],
        [ 1., nan,  1.,  1.,  2.],
        [ 2., nan,  2.,  2.,  2.],
        [ 1., nan, nan,  1.,  1.],
        [ 1.,  2.,  1.,  1., nan],
        [nan,  2.,  1., nan, nan],
        [nan,  2.,  2., nan,  2.],
        [ 2.,  2.,  2.,  1.,  2.],
        [ 2.,  2.,  1.,  2., nan],
        [ 2.,  2.,  1.,  2.,  2.],
        [ 1.,  1.,  2.,  2.,  2.],
        [ 1.,  2.,  1.,  1.,  1.],
        [ 2.,  1.,  2.,  1.,  2.],
        [ 1., nan, nan,  2.,  2.],
        [ 1.,  2.,  2., nan,  2.],
        [ 1.,  1., nan,  2.,  2.],
        [ 2.,  1.,  1.,  1.,  1.],
        [ 2.,  1.,  2.,  1.,  1.]]),
 array([0.57019675, 0.03842543, 0.43860152, 0.63427407, 0.9883738 ,
        0.95894927, 0.10204481, 0.6527903 , 0.20887676, 0.6350589 ,
        0.16130951, 0.9952996 , 0.6531083 , 0.58185035, 0.2532916 ,
        0.4143686 , 0.46631077, 0.4746975 , 0.2444256 , 0.6235101 ]))

(array([[ 2.,  2.],
        [nan,  2.],
        [ 1.,  2.],
        [ 2.,  2.],
        [ 1.,  1.],
        [ 1.,  2.],
        [ 1., nan],
        [ 2.,  2.],
        [nan,  2.],
        [ 1.,  2.],
        [ 1.,  1.],
        [ 1.,  2.],
        [ 1.,  2.],
        [ 1.,  2.],
        [ 1.,  2.],
        [nan,  1.],
        [ 1.,  2.],
        [ 2., nan],
        [ 1.,  2.],
        [ 1.,  1.]]),
 array([0.3654961 , 0.9755215 , 0.01662797, 0.8558034 , 0.23074234,
        0.01171408, 0.7649117 , 0.35997805, 0.9441235 , 0.72999054,
        0.7499992 , 0.17162968, 0.3394038 , 0.5210366 , 0.48954895,
        0.05433799, 0.33898512, 0.19999653, 0.17949027, 0.01852179]))

## Linear Algebra
pg 53

In [39]:
A=np.arange(20).reshape(5,4)
A,A.mean(axis=0),A.mean(axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]),
 array([ 8.,  9., 10., 11.]),
 array([ 1.5,  5.5,  9.5, 13.5, 17.5]))

In [45]:
A.sum(),A.sum(axis=1),A.sum(axis=1,keepdims=True)

(array(190.),
 array([ 6., 22., 38., 54., 70.]),
 array([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]]))

In [48]:
A/A.sum(axis=1,keepdims=True),A.cumsum(axis=1)

(array([[0.        , 0.16666667, 0.33333334, 0.5       ],
        [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
        [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
        [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
        [0.22857143, 0.24285714, 0.25714287, 0.27142859]]),
 array([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]]))

In [55]:
A1=np.array([1,2,3,4]).reshape(2,2)
B1=np.array([-1,3,4,2]).reshape(2,2)
A1,B1,A1*B1,np.dot(A1,B1),np.dot(B1,A1)

(array([[1., 2.],
        [3., 4.]]),
 array([[-1.,  3.],
        [ 4.,  2.]]),
 array([[-1.,  6.],
        [12.,  8.]]),
 array([[ 7.,  7.],
        [13., 17.]]),
 array([[ 8., 10.],
        [10., 16.]]))

In [58]:
A1=np.array([1,2,3,4])
B1=np.array([-1,3,4,2])
A1,B1,A1*B1,np.dot(A1,B1)

(array([1., 2., 3., 4.]),
 array([-1.,  3.,  4.,  2.]),
 array([-1.,  6., 12.,  8.]),
 array(25.))

In [74]:
y=np.ones(4)
x.reshape(1,3), y

(array([[1., 2., 3.]]), array([1., 1., 1., 1.]))