## Avaliando [Crash Course](https://mxnet.apache.org/versions/master/api/python/docs/tutorials/getting-started/crash-course/1-nparray.html)


### Step1

In [1]:
import mxnet as mx
from mxnet import np, npx
from mxnet.gluon import nn

npx.set_np()

In [2]:
np.array(((1,2,3),(5,6,7)))

[17:49:02] /home/mertins/Desenvolvimento/C/Terceiros/mxnet/src/storage/storage.cc:202: Using Pooled (Naive) StorageManager for CPU


array([[1., 2., 3.],
       [5., 6., 7.]])

In [3]:
x=np.full((2,3),1)
x


array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
y=np.random.uniform(-1,1,(2,3))
y

array([[0.09762704, 0.18568921, 0.43037868],
       [0.6885315 , 0.20552671, 0.71589124]])

In [5]:
x.shape, x.size, x.dtype

((2, 3), 6, dtype('float32'))

In [6]:
y[:,1:3]

array([[0.18568921, 0.43037868],
       [0.20552671, 0.71589124]])

In [7]:
type(x),type(x.asnumpy())

(mxnet.numpy.ndarray, numpy.ndarray)